---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generic-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/git67/k8s-argocd-bootstrap.git
    path: generic/apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
